export const CONFIGURATION_MODULE_NAME = 'czvinyl';

export const SEARCH_PLACES = [
	'package.json',
	`.${CONFIGURATION_MODULE_NAME}rc`,
	`.${CONFIGURATION_MODULE_NAME}rc.json`,
	`.${CONFIGURATION_MODULE_NAME}rc.yaml`,
	`.${CONFIGURATION_MODULE_NAME}rc.yml`,
	`.${CONFIGURATION_MODULE_NAME}rc.js`,
	`.${CONFIGURATION_MODULE_NAME}rc.ts`,
	`.${CONFIGURATION_MODULE_NAME}rc.cjs`,
	`${CONFIGURATION_MODULE_NAME}.config.js`,
	`${CONFIGURATION_MODULE_NAME}.config.ts`,
	`${CONFIGURATION_MODULE_NAME}.config.cjs`,
];
